# Generated by Django 4.1 on 2022-08-15 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0003_alter_documentownership_values'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EligibilityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_value', models.IntegerField(default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.attribute')),
            ],
        ),
        migrations.CreateModel(
            name='Logic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_claims', models.IntegerField(auto_created=True, default=0)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=4096)),
                ('amount', models.IntegerField()),
                ('starting', models.DateTimeField()),
                ('duration', models.DateTimeField(blank=True, null=True)),
                ('applications', models.ManyToManyField(blank=True, through='scholarships.Application', to=settings.AUTH_USER_MODEL)),
                ('attribute_checks', models.ManyToManyField(blank=True, through='scholarships.EligibilityCheck', to='documents.attribute')),
            ],
        ),
        migrations.AddField(
            model_name='eligibilitycheck',
            name='logic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarships.logic'),
        ),
        migrations.AddField(
            model_name='eligibilitycheck',
            name='scholarship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarships.scholarship'),
        ),
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarships.application')),
                ('eligibility_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarships.eligibilitycheck')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='eligibilities',
            field=models.ManyToManyField(blank=True, through='scholarships.Eligibility', to='scholarships.eligibilitycheck'),
        ),
        migrations.AddField(
            model_name='application',
            name='scholarship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarships.scholarship'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
