# Generated by Django 4.1 on 2022-08-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='no_of_claims',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='max_claims',
            field=models.IntegerField(default=0),
        ),
    ]
