# Generated by Django 4.1 on 2022-08-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eligibility',
            options={'verbose_name_plural': 'Eligibilities'},
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='duration',
            field=models.DurationField(),
        ),
    ]
