# Generated by Django 4.1 on 2022-08-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_alter_eligibility_options_alter_scholarship_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibilitycheck',
            name='edge_value',
            field=models.CharField(max_length=256),
        ),
    ]
