# Generated by Django 4.1 on 2022-08-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_remove_scholarship_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='max_claims',
            field=models.IntegerField(),
        ),
    ]
