# Generated by Django 4.1 on 2022-08-15 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_documentownership_values'),
        ('scholarships', '0003_alter_eligibilitycheck_edge_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilitycheck',
            name='edge_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.option'),
        ),
        migrations.AlterField(
            model_name='eligibilitycheck',
            name='edge_value',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
