# Generated by Django 4.1 on 2022-08-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0003_alter_scholarship_max_claims'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='auto_pay',
            field=models.BooleanField(default=False),
        ),
    ]
