# Generated by Django 4.1 on 2022-08-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Creator', 'Creator'), ('Issuer', 'Issuer')], default='Student', max_length=16),
        ),
    ]
