# Generated by Django 4.1 on 2022-08-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='_type',
            field=models.CharField(max_length=32),
        ),
    ]
