# Generated by Django 4.1 on 2022-08-15 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_attribute__type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentownership',
            name='values',
            field=models.ManyToManyField(blank=True, related_name='owned_documents', to='documents.value'),
        ),
    ]
